name: My Design Site
favicon: null
layout_spectrum: 0.7568276466336101
typography_spectrum: 0.5777914349455386
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.15502495667897165
  lightness: 0.7326301585417241
  saturation: 0.2128577958792448
  rhythmicContrast: 0.518203129991889
purpose: []
